import {
  Controller,
  Get,
  HttpException,
  HttpStatus,
  Logger,
  Param,
  Query,
  Req,
  Res,
  UseGuards,
} from '@nestjs/common';

import { isDefined } from 'twenty-shared/utils';
import type { Request, Response } from 'express';

import { JwtWrapperService } from 'src/engine/core-modules/jwt/services/jwt-wrapper.service';
import { GlobalWorkspaceOrmManager } from 'src/engine/twenty-orm/global-workspace-datasource/global-workspace-orm.manager';
import { NoPermissionGuard } from 'src/engine/guards/no-permission.guard';
import { PublicEndpointGuard } from 'src/engine/guards/public-endpoint.guard';
import { buildSystemAuthContext } from 'src/engine/twenty-orm/utils/build-system-auth-context.util';
import { type CampaignWorkspaceEntity } from 'src/modules/campaign/standard-objects/campaign.workspace-entity';

// Public web-preview endpoint for marketing email designs. Lets a user
// share a draft campaign with a stakeholder who isn't a Twenty member —
// they open the URL, see exactly what the email will look like, no
// login required.
//
// Auth: a short-lived JWT generated by the campaign-action resolver's
// generateCampaignPreviewLink mutation. Token payload is
// { sub: 'campaign-preview', workspaceId, campaignId }; verification
// failures return 404 so the existence of campaigns isn't leaked.
//
// Tokens substituted with sample values — the same pattern sendTestEmail
// uses — so the preview shows realistic content without exposing real
// recipient data.

const PREVIEW_TOKEN_SUBJECT = 'campaign-preview';

const SAMPLE_SUBSTITUTIONS: Record<string, string> = {
  '{{contact.firstName}}': 'Alex',
  '{{contact.lastName}}': 'Sample',
  '{{contact.fullName}}': 'Alex Sample',
  '{{contact.email}}': 'alex@example.com',
  '{{contact.jobTitle}}': 'Director',
  '{{contact.city}}': 'San Francisco',
  '{{contact.companyName}}': 'Sample Co.',
  '{{unsubscribe_link}}': '#preview-unsubscribe',
};

const KNOWN_TOKEN_INNER =
  '(?:contact\\.(?:firstName|lastName|fullName|email|jobTitle|city|companyName)|unsubscribe_link)';
const TOKEN_NORMALIZE_RE = new RegExp(
  `\\{\\{\\s*(${KNOWN_TOKEN_INNER})\\s*\\}\\}`,
  'g',
);

const substituteSample = (html: string): string => {
  // Normalize whitespace-padded tokens to canonical form, then literal-
  // replace each. Same approach as the campaign-executor for sends.
  let out = html.replace(TOKEN_NORMALIZE_RE, '{{$1}}');
  for (const [key, value] of Object.entries(SAMPLE_SUBSTITUTIONS)) {
    out = out.split(key).join(value);
  }
  return out;
};

@Controller()
export class CampaignPublicController {
  private readonly logger = new Logger(CampaignPublicController.name);

  constructor(
    private readonly globalWorkspaceOrmManager: GlobalWorkspaceOrmManager,
    private readonly jwtWrapperService: JwtWrapperService,
  ) {}

  @Get('campaigns/preview/:workspaceId/:campaignId')
  @UseGuards(PublicEndpointGuard, NoPermissionGuard)
  async getCampaignPreview(
    @Param('workspaceId') workspaceId: string,
    @Param('campaignId') campaignId: string,
    @Query('token') token: string | undefined,
    @Req() _req: Request,
    @Res() res: Response,
  ) {
    if (!isDefined(token) || token === '') {
      throw new HttpException('Not found', HttpStatus.NOT_FOUND);
    }

    let payload: {
      sub?: string;
      workspaceId?: string;
      campaignId?: string;
    };
    try {
      payload = await this.jwtWrapperService.verifyJwtToken(token);
    } catch {
      throw new HttpException('Not found', HttpStatus.NOT_FOUND);
    }

    if (
      payload.sub !== PREVIEW_TOKEN_SUBJECT ||
      payload.workspaceId !== workspaceId ||
      payload.campaignId !== campaignId
    ) {
      throw new HttpException('Not found', HttpStatus.NOT_FOUND);
    }

    const authContext = buildSystemAuthContext(workspaceId);

    const campaign =
      await this.globalWorkspaceOrmManager.executeInWorkspaceContext(
        async () => {
          const campaignRepository =
            await this.globalWorkspaceOrmManager.getRepository<CampaignWorkspaceEntity>(
              workspaceId,
              'campaign',
              { shouldBypassPermissionChecks: true },
            );
          return campaignRepository.findOne({ where: { id: campaignId } });
        },
        authContext,
      );

    if (!isDefined(campaign)) {
      throw new HttpException('Not found', HttpStatus.NOT_FOUND);
    }

    const html = substituteSample(campaign.bodyHtml ?? '');

    res.setHeader('Content-Type', 'text/html; charset=utf-8');
    // Don't allow this preview to be cached publicly — the underlying
    // draft is mutable and a stakeholder reloading should always see
    // the latest. Token-based access already prevents arbitrary lookups.
    res.setHeader('Cache-Control', 'private, no-store');
    // Defense in depth: don't let preview pages be embedded in third-
    // party iframes outside the user's flow.
    res.setHeader('X-Frame-Options', 'SAMEORIGIN');
    res.send(html);
  }
}
