import { msg } from '@lingui/core/macro';
import {
  DateDisplayFormat,
  FieldMetadataType,
  RelationType,
} from 'twenty-shared/types';

import { type FlatFieldMetadata } from 'src/engine/metadata-modules/flat-field-metadata/types/flat-field-metadata.type';
import { type AllStandardObjectFieldName } from 'src/engine/workspace-manager/twenty-standard-application/types/all-standard-object-field-name.type';
import { i18nLabel } from 'src/engine/workspace-manager/twenty-standard-application/utils/i18n-label.util';
import {
  type CreateStandardFieldArgs,
  createStandardFieldFlatMetadata,
} from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-field-flat-metadata.util';
import { createStandardRelationFieldFlatMetadata } from 'src/engine/workspace-manager/twenty-standard-application/utils/field-metadata/create-standard-relation-field-flat-metadata.util';
import { getTsVectorColumnExpressionFromFields } from 'src/engine/workspace-manager/utils/get-ts-vector-column-expression.util';
import { SEARCH_FIELDS_FOR_FORM } from 'src/modules/form/standard-objects/form.workspace-entity';

export const buildFormStandardFlatFieldMetadatas = ({
  now,
  objectName,
  workspaceId,
  standardObjectMetadataRelatedEntityIds,
  dependencyFlatEntityMaps,
  twentyStandardApplicationId,
}: Omit<CreateStandardFieldArgs<'form', FieldMetadataType>, 'context'>): Record<
  AllStandardObjectFieldName<'form'>,
  FlatFieldMetadata
> => ({
  // Base fields
  id: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'id',
      type: FieldMetadataType.UUID,
      label: i18nLabel(msg`Id`),
      description: i18nLabel(msg`Id`),
      icon: 'Icon123',
      isSystem: true,
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 'uuid',
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Creation date`),
      description: i18nLabel(msg`Creation date`),
      icon: 'IconCalendar',
      isSystem: true,
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 'now',
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Last update`),
      description: i18nLabel(msg`Last time the record was changed`),
      icon: 'IconCalendarClock',
      isSystem: true,
      isNullable: false,
      isUIReadOnly: true,
      defaultValue: 'now',
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  deletedAt: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'deletedAt',
      type: FieldMetadataType.DATE_TIME,
      label: i18nLabel(msg`Deleted at`),
      description: i18nLabel(msg`Date when the record was deleted`),
      icon: 'IconCalendarMinus',
      isSystem: true,
      isNullable: true,
      isUIReadOnly: true,
      settings: {
        displayFormat: DateDisplayFormat.RELATIVE,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // System fields
  position: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'position',
      type: FieldMetadataType.POSITION,
      label: i18nLabel(msg`Position`),
      description: i18nLabel(msg`Form record position`),
      icon: 'IconHierarchy2',
      isSystem: true,
      isNullable: false,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  createdBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'createdBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Created by`),
      description: i18nLabel(msg`The creator of the record`),
      icon: 'IconCreativeCommonsSa',
      isSystem: true,
      isUIReadOnly: true,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  updatedBy: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'updatedBy',
      type: FieldMetadataType.ACTOR,
      label: i18nLabel(msg`Updated by`),
      description: i18nLabel(
        msg`The workspace member who last updated the record`,
      ),
      icon: 'IconUserCircle',
      isSystem: true,
      isUIReadOnly: true,
      isNullable: false,
      defaultValue: {
        source: "'MANUAL'",
        name: "'System'",
        workspaceMemberId: null,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Form-specific fields
  name: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'name',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Name`),
      description: i18nLabel(msg`Form name`),
      icon: 'IconForms',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  description: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'description',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Description`),
      description: i18nLabel(msg`Form description`),
      icon: 'IconNotes',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  status: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'status',
      type: FieldMetadataType.SELECT,
      label: i18nLabel(msg`Status`),
      description: i18nLabel(msg`Form status`),
      icon: 'IconStatusChange',
      isNullable: false,
      defaultValue: "'DRAFT'",
      options: [
        {
          id: 'a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d',
          value: 'DRAFT',
          label: i18nLabel(msg`Draft`),
          position: 0,
          color: 'sky',
        },
        {
          id: 'b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e',
          value: 'PUBLISHED',
          label: i18nLabel(msg`Published`),
          position: 1,
          color: 'green',
        },
        {
          id: '41ecfe3d-1115-436d-97cb-49fc2f05d9a4',
          value: 'ARCHIVED',
          label: i18nLabel(msg`Archived`),
          position: 2,
          color: 'gray',
        },
      ],
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  fieldsConfig: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'fieldsConfig',
      type: FieldMetadataType.RAW_JSON,
      label: i18nLabel(msg`Fields Configuration`),
      description: i18nLabel(msg`JSON configuration of form fields`),
      icon: 'IconSettings',
      isNullable: true,
      isSystem: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  submissionCount: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'submissionCount',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Submissions`),
      description: i18nLabel(msg`Total number of form submissions`),
      icon: 'IconInbox',
      isNullable: false,
      defaultValue: 0,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  thankYouMessage: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'thankYouMessage',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Thank You Message`),
      description: i18nLabel(
        msg`Message shown after successful form submission`,
      ),
      icon: 'IconCheck',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  notifyOnSubmission: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'notifyOnSubmission',
      type: FieldMetadataType.BOOLEAN,
      label: i18nLabel(msg`Notify on Submission`),
      description: i18nLabel(
        msg`Whether to send email notification on new submission`,
      ),
      icon: 'IconBell',
      isNullable: false,
      defaultValue: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  notificationEmail: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'notificationEmail',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Notification Email`),
      description: i18nLabel(msg`Email address to notify on new submissions`),
      icon: 'IconAt',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  redirectUrl: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'redirectUrl',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Redirect URL`),
      description: i18nLabel(
        msg`URL to redirect to after successful form submission`,
      ),
      icon: 'IconExternalLink',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  sendConfirmationEmail: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'sendConfirmationEmail',
      type: FieldMetadataType.BOOLEAN,
      label: i18nLabel(msg`Send Confirmation Email`),
      description: i18nLabel(
        msg`Whether to send a confirmation email to the submitter`,
      ),
      icon: 'IconMailForward',
      isNullable: false,
      defaultValue: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  confirmationEmailSubject: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'confirmationEmailSubject',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Confirmation Email Subject`),
      description: i18nLabel(msg`Subject line for confirmation emails`),
      icon: 'IconAt',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  confirmationEmailBody: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'confirmationEmailBody',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Confirmation Email Body`),
      description: i18nLabel(msg`HTML body for confirmation emails`),
      icon: 'IconMail',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  autoCreatePerson: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'autoCreatePerson',
      type: FieldMetadataType.BOOLEAN,
      label: i18nLabel(msg`Auto-create Person on submission`),
      description: i18nLabel(
        msg`Whether to auto-create a Person record when this form is submitted (uses email + name fields if present)`,
      ),
      icon: 'IconUserPlus',
      isNullable: false,
      defaultValue: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  // Bot-protection toggle. When true, the public submit endpoint
  // requires a valid Cloudflare Turnstile token AND (if
  // honeypotFieldName is set) an empty honeypot field. Default false
  // so existing forms keep working without configuration.
  botProtectionEnabled: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'botProtectionEnabled',
      type: FieldMetadataType.BOOLEAN,
      label: i18nLabel(msg`Bot protection`),
      description: i18nLabel(
        msg`Require a valid Cloudflare Turnstile token (and honor the honeypot field) on every submission. Default off.`,
      ),
      icon: 'IconShieldCheck',
      isNullable: false,
      defaultValue: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  // Cloudflare Turnstile site key (public) for this form. Set this on
  // the form so different forms can use different Turnstile widgets.
  // The matching secret key lives in the CLOUDFLARE_TURNSTILE_SECRET_KEY
  // server env var.
  botProtectionSiteKey: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'botProtectionSiteKey',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Turnstile site key`),
      description: i18nLabel(
        msg`Cloudflare Turnstile site key (public) embedded in the form. Required when bot protection is enabled.`,
      ),
      icon: 'IconKey',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  // Honeypot field name. If set, the submit endpoint silently drops
  // any submission whose fields[honeypotFieldName] contains a
  // non-empty string. Bots auto-fill all fields; humans don't see
  // CSS-hidden inputs.
  honeypotFieldName: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'honeypotFieldName',
      type: FieldMetadataType.TEXT,
      label: i18nLabel(msg`Honeypot field name`),
      description: i18nLabel(
        msg`Name of a hidden form field that legitimate users will leave blank. Bots that auto-fill it get silently rejected.`,
      ),
      icon: 'IconBug',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  // Native bot-protection layers, all server-validated at submit.
  requireFormLoadToken: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'requireFormLoadToken',
      type: FieldMetadataType.BOOLEAN,
      label: i18nLabel(msg`Require form-load token`),
      description: i18nLabel(
        msg`Require submissions to include the signed JWT issued by GET /schema. Defeats bots that POST without rendering the form.`,
      ),
      icon: 'IconKey',
      isNullable: false,
      defaultValue: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  minSubmitTimeSeconds: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'minSubmitTimeSeconds',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Minimum submit time (seconds)`),
      description: i18nLabel(
        msg`Reject submissions whose form-load token age is below this floor. Catches instant-fire bots. Default 2.`,
      ),
      icon: 'IconClock',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  rateLimitPerMinute: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'rateLimitPerMinute',
      type: FieldMetadataType.NUMBER,
      label: i18nLabel(msg`Rate limit (per IP per minute)`),
      description: i18nLabel(
        msg`Max submissions per source IP per rolling 60s window. 0 or null disables.`,
      ),
      icon: 'IconBolt',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  allowedOrigins: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'allowedOrigins',
      type: FieldMetadataType.ARRAY,
      label: i18nLabel(msg`Allowed origins`),
      description: i18nLabel(
        msg`Allowlist of Origin / Referer hosts permitted to submit. Empty / null = all allowed. e.g. ["https://customer-site.com"].`,
      ),
      icon: 'IconWorld',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  rejectDisposableEmails: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'rejectDisposableEmails',
      type: FieldMetadataType.BOOLEAN,
      label: i18nLabel(msg`Reject disposable emails`),
      description: i18nLabel(
        msg`Drop submissions whose email ends in a known temp-mail domain (mailinator, tempmail, etc.).`,
      ),
      icon: 'IconMailX',
      isNullable: false,
      defaultValue: false,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  // Tags merged into the auto-created Person's `tags` array on
  // submission. Only applied when autoCreatePerson is true. Empty / null
  // means no tagging. Pattern mirrors additionalMarketingCampaignIds.
  tagsToApplyOnSubmission: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'tagsToApplyOnSubmission',
      type: FieldMetadataType.ARRAY,
      label: i18nLabel(msg`Tags to apply on submission`),
      description: i18nLabel(
        msg`Free-form tag strings to add to a Person's tags array when this form auto-creates them.`,
      ),
      icon: 'IconTags',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  // Many-to-many: any number of additional MarketingCampaign IDs this
  // form belongs to (beyond the primary marketingCampaignId FK).
  additionalMarketingCampaignIds: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'additionalMarketingCampaignIds',
      type: FieldMetadataType.ARRAY,
      label: i18nLabel(msg`Additional Marketing Campaigns`),
      description: i18nLabel(
        msg`UUIDs of additional MarketingCampaign records this form belongs to (beyond the primary FK).`,
      ),
      icon: 'IconCirclesRelation',
      isNullable: true,
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
  searchVector: createStandardFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      fieldName: 'searchVector',
      type: FieldMetadataType.TS_VECTOR,
      label: i18nLabel(msg`Search vector`),
      description: i18nLabel(msg`Field used for full-text search`),
      icon: 'IconUser',
      isSystem: true,
      isNullable: true,
      settings: {
        generatedType: 'STORED',
        asExpression: getTsVectorColumnExpressionFromFields(
          SEARCH_FIELDS_FOR_FORM,
        ),
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),

  // Relation fields
  formSubmissions: createStandardRelationFieldFlatMetadata({
    objectName,
    workspaceId,
    context: {
      type: FieldMetadataType.RELATION,
      morphId: null,
      fieldName: 'formSubmissions',
      label: i18nLabel(msg`Submissions`),
      description: i18nLabel(msg`Form submissions`),
      icon: 'IconInbox',
      isNullable: true,
      targetObjectName: 'formSubmission',
      targetFieldName: 'form',
      settings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    standardObjectMetadataRelatedEntityIds,
    dependencyFlatEntityMaps,
    twentyStandardApplicationId,
    now,
  }),
});
